In [18]:
import yt
from matplotlib import rc_context
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import numpy as np
print(yt.__version__)

step = 1

plot_file_path = "./data_mixture/plt" + f"{step:05d}" # total 9 digits number for step info 
ds = yt.load(plot_file_path)
print(ds.field_list)
#profile_data = ds.all_data()[("boxlib", "struct_fact_rho_rho")].to_ndarray()
profile_data = ds.covering_grid(
    level=0, left_edge=ds.domain_left_edge, dims=ds.domain_dimensions
)
rho = profile_data["boxlib", "rhoA"] # density
phi = profile_data["boxlib", "rhoB"] # potential
ufx = profile_data["boxlib", "uAx"] # magnitude
print(rho)

yt : [INFO     ] 2025-04-13 06:00:01,292 Parameters: current_time              = 1.0
yt : [INFO     ] 2025-04-13 06:00:01,292 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2025-04-13 06:00:01,293 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-04-13 06:00:01,293 Parameters: domain_right_edge         = [1. 1. 1.]


4.4.0
[('boxlib', 'mf10'), ('boxlib', 'mf11'), ('boxlib', 'mf12'), ('boxlib', 'mf13'), ('boxlib', 'mf14'), ('boxlib', 'mf15'), ('boxlib', 'mf16'), ('boxlib', 'mf17'), ('boxlib', 'mf18'), ('boxlib', 'mf4'), ('boxlib', 'mf5'), ('boxlib', 'mf6'), ('boxlib', 'mf7'), ('boxlib', 'mf8'), ('boxlib', 'mf9'), ('boxlib', 'mg10'), ('boxlib', 'mg11'), ('boxlib', 'mg12'), ('boxlib', 'mg13'), ('boxlib', 'mg14'), ('boxlib', 'mg15'), ('boxlib', 'mg16'), ('boxlib', 'mg17'), ('boxlib', 'mg18'), ('boxlib', 'mg4'), ('boxlib', 'mg5'), ('boxlib', 'mg6'), ('boxlib', 'mg7'), ('boxlib', 'mg8'), ('boxlib', 'mg9'), ('boxlib', 'rhoA'), ('boxlib', 'rhoB'), ('boxlib', 'uAx'), ('boxlib', 'uAy'), ('boxlib', 'uAz'), ('boxlib', 'uBx'), ('boxlib', 'uBy'), ('boxlib', 'uBz')]
[[[1.00420679 1.00420679 1.00420679 ... 1.00420679 1.00420679 1.00420679]
  [1.00420679 1.00420679 1.00420679 ... 1.00420679 1.00420679 1.00420679]
  [1.00420679 1.00420679 1.00420679 ... 1.00420679 1.00420679 1.00420679]
  ...
  [1.00420679 1.0042067